### ISSUE TITLE
Handle Nominal Values for Attributes

### ISSUE THREAD

**Issue by Penchant** [DanielChurch/Machine-Learning-Soft-Computing-Project-1#2]
Attributes currently only detect type as either numeric or string, but nominal values, which are essentially enumerations, is another valid attribute type which is not currently accounted for.

**Comment by DanielChurch** [comment]
The data sets we chose do not need the use of nominal values.  Great suggestion for making it work for every data set, but due to the complexity of this issue and our time constraint, it would add it is not worth our time in this project.
